version: '3.8'
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - redis  # добавляем зависимость

  php:
    build: .
    container_name: lab5_php
    volumes:
      - ./code:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:8.0
    container_name: lab5_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab5_db
      MYSQL_USER: lab5_user
      MYSQL_PASSWORD: lab5_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: lab5_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  redis:  # новый сервис
    image: redis:7-alpine
    container_name: lab5_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:  # новый volume