services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab7_nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - redis
      - rabbitmq

  php:
    build: .
    container_name: lab7_php
    volumes:
      - ./code:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:8.0
    container_name: lab7_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab5_db
      MYSQL_USER: lab5_user
      MYSQL_PASSWORD: lab5_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: lab7_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  redis:
    image: redis:7.2-alpine
    container_name: lab7_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: lab7_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  kafka:
    image: confluentinc/cp-kafka:7.5.2
    container_name: lab7_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.2
    container_name: lab7_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

volumes:
  db_data:
  redis_data: