version: '3.8'
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - redis
      - elasticsearch
      - clickhouse

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./code:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:8.0
    container_name: lab6_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab6_db
      MYSQL_USER: lab6_user
      MYSQL_PASSWORD: lab6_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: lab6_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: lab6_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: lab6_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: lab6_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=lab6_stats
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=lab6_pass
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  db_data:
  redis_data:
  elasticsearch_data:
  clickhouse_data: