services:
  web:
    image: nginx:1.27-alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./code:/var/www/html
      - ./vendor:/var/www/html/vendor
    expose:
      - "9000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: lab6_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab6_db
      MYSQL_USER: lab6_user
      MYSQL_PASSWORD: lab6_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: lab6_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    container_name: lab6_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
  redis_data: