version: '3.8'
services:
  nginx:
    image: nginx:1.27-alpine
    container_name: lab7_nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - redis
      - rabbitmq
      - kafka

  php:
    build: .
    container_name: lab7_php
    volumes:
      - ./code:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:8.0
    container_name: lab7_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab5_db      
      MYSQL_USER: lab5_user        
      MYSQL_PASSWORD: lab5_pass    
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: lab7_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  redis:
    image: redis:7.2-alpine
    container_name: lab7_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: lab7_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: lab7_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5        
    container_name: lab7_kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

volumes:
  db_data:
  redis_data: